### ISSUE TITLE
Why spleeter doesn't work

### ISSUE THREAD

**Issue by Zakirzhan** [JeffreyCA/spleeter-web#107]
Hello!
AFter uploading mp3 script waits.
Showing message: In queue
 I am waiting more that one hour, but nothing happened

It's api's response:
{
    "id": "6222892a-bcae-49cb-bed0-5a193361421e",
    "source_track": "2ffae5d6-62e4-4af1-8d63-834ab3ad9301",
    "separator": "spleeter",
    "extra_info": [
        "256 kbps",
        "4 stems (16 kHz)"
    ],
    "artist": "Taq tara",
    "title": "Kisla",
    "vocals_url": "",
    "other_url": "",
    "bass_url": "",
    "drums_url": "",
    "status": "Queued",
    "error": "",
    "date_created": "2021-12-13T10:40:47.057898Z"
}

**Comment by Zakirzhan** [comment]
When I did "docker-compose up -d" 

Recreating e7ae9817d2b9_spleeter-web_celery-fast_1 ... 
Recreating 62965d027b83_spleeter-web_celery-slow_1 ... 
Recreating 62965d027b83_spleeter-web_celery-slow_1 ... error
Starting spleeter-web_nginx_1                      ... 
Recreating e7ae9817d2b9_spleeter-web_celery-fast_1 ... error
ERROR: for 62965d027b83_spleeter-web_celery-slow_1  Cannot create container for service celery-slow: Unknown runtime specified nvidia

ERROR: for e7ae9817d2b9_spleeter-web_celery-fast_1  Cannot create container for Starting spleeter-web_nginx_1                      ... done

ERROR: for celery-slow  Cannot create container for service celery-slow: Unknown runtime specified nvidia

ERROR: for celery-fast  Cannot create container for service celery-fast: Unknown runtime specified nvidia
ERROR: Encountered errors while bringing up the project.

**Comment by JeffreyCA** [comment]
Hi, what's the full command you are running? If you are using the GPU images, see if this helps: https://github.com/NVIDIA/nvidia-docker/issues/838

**Comment by Zakirzhan** [comment]
> Привет, какая у вас полная команда? Если вы используете образы графического процессора, посмотрите, поможет ли это: [NVIDIA / nvidia-docker # 838](https://github.com/NVIDIA/nvidia-docker/issues/838)
