### ISSUE TITLE
Can't upload YT videos with Chinese characters!

### ISSUE THREAD

**Issue by piwawa** [JeffreyCA/spleeter-web#1087]
![image](https://github.com/JeffreyCA/spleeter-web/assets/46926496/5b0bd181-4ff9-4d4a-b82b-1703be7c4851)

**Comment by piwawa** [comment]
Youtube:
https://www.youtube.com/watch?v=iA0Uxzs_Qow

**Comment by JeffreyCA** [comment]
Hi, can you please share the console output/logs of the "fast_queue" celery worker?

**Comment by piwawa** [comment]
After i setting envs, It works.

```
Environment="LANG=en_US.UTF-8"
Environment="LC_ALL=en_US.UTF-8"
```
