### ISSUE TITLE
How to give access to other domains?

### ISSUE THREAD

**Issue by Zakirzhan** [JeffreyCA/spleeter-web#111]
hey!
how to get access to cors from other domains?
For instance: I want to use api.site.com like backend,
and site.com like frontend, I'll send requests via jquery for downloading youtube videos, creating mixes (separating), and for getting urls to files.

But when I run js code from site.com
There is one problem:
Access to XMLHttpRequest at 'https://api.site.com/api/source-track/youtube/' from origin 'https://site.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

I tried to install [django cors headers](https://stackoverflow.com/questions/35760943/how-can-i-enable-cors-on-django-rest-framework#:~:text=The%20link%20you%20referenced%20in%20your%20question%20recommends%20using%20django%2Dcors%2Dheaders%2C%20whose%20documentation%20says%20to%20install%20the%20library)
BUT it doesn't work, pls help me

**Comment by Zakirzhan** [comment]
and how to separate not to 4 stems (other,bass,drums and vocal) but to 2 stems (vocal and instrumental) ?

**Comment by JeffreyCA** [comment]
Have you tried playing around with the `CORS_ALLOWED_ORIGINS` setting to allow requests from `https://site.com`?

> and how to separate not to 4 stems (other,bass,drums and vocal) but to 2 stems (vocal and instrumental) ?

This is not currently supported, only 4-stem separation works.

**Comment by Zakirzhan** [comment]
I installed django-cors-header
by running this code:
`python -m pip install django-cors-headers`

I've added these lines to file django_react/settings_docker.py
```
INSTALLED_APPS = (
    ...
    'corsheaders',
    ...
)
MIDDLEWARE = [
    ...,
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    ...,
]


ALLOWED_ORIGINS = [
    "*"
]


CORS_ALLOW_ALL_ORIGINS = True # If this is used then `CORS_ALLOWED_ORIGINS` will not have any effect
CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with'
]
```

**Comment by JeffreyCA** [comment]
I don't see any problems with the above. 

Are you using Docker? And where did you run `python -m pip install django-cors-headers`? You may need to add `django-cors-headers` to `requirements.txt`.

**Comment by Zakirzhan** [comment]
root@e20135:~/karaoke# python3 -m pip install -r requirements.txt
Ignoring python-magic-bin: markers 'sys_platform != "linux"' don't match your environment
Requirement already satisfied: django-cors-headers in /usr/local/lib/python3.7/dist-packages (from -r requirements.txt (line 1)) (3.10.1)
Collecting demucs==3.0.3 (from -r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/17/24/3b75e03243651603b95d8dbdb99eba104a464d3e8ca26d1ad54d95a985c5/demucs-3.0.3.tar.gz
Collecting absl-py==0.12.0 (from -r requirements.txt (line 3))
  Using cached https://files.pythonhosted.org/packages/92/c9/ef0fae29182d7a867d203f0eff8296b60da92098cc41db33a434f4be84bf/absl_py-0.12.0-py3-none-any.whl
Collecting amqp==5.0.6 (from -r requirements.txt (line 4))

**Comment by JeffreyCA** [comment]
Try adding `corsheaders.middleware.CorsMiddleware` as the first item in `MIDDLEWARE`?

**Comment by Zakirzhan** [comment]
> Try adding `corsheaders.middleware.CorsMiddleware` as the first item in `MIDDLEWARE`?
INSTALLED_APPS = (
    'corsheaders',
...
)

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
...]

It was as the first item in Middleware

**Comment by JeffreyCA** [comment]
Hmm maybe try checking the network requests and headers in your browser's Network dev tools. Are all requests missing that Access-Control-Allow-Origin header? Could also be something with the Nginx config
