### ISSUE TITLE
X-UMX: What does softmask do?

### ISSUE THREAD

**Issue by jtagcat** [JeffreyCA/spleeter-web#125]
https://github.com/JeffreyCA/spleeterweb-xumx

![image](https://user-images.githubusercontent.com/38327267/153751135-a05de8cb-c267-41a0-b210-9a174140ef0e.png)

(todo: docs in UI?)

**Comment by JeffreyCA** [comment]
From https://github.com/JeffreyCA/spleeterweb-xumx/blob/ddcc75e97ce8b374964347e216020e1faa6bc009/xumx/test.py#L64-L68:

```
    softmask: boolean
        if activated, then the initial estimates for the sources will
        be obtained through a ratio mask of the mixture STFT, and not
        by using the default behavior of reconstructing waveforms
        by using the mixture phase, defaults to False
```
