### ISSUE TITLE
Unable to Export Audio

### ISSUE THREAD

**Issue by F1zzyD** [JeffreyCA/spleeter-web#1333]
After successfully uploading and mixing an audio file, Spleeter Web refuses to export the audio, claiming:
"SharedArrayBuffer is not defined. Check ENABLE_CROSS_ORIGIN_HEADERS=1 is set and HTTPS is enabled.

I have `ENABLE_CROSS_ORIGIN_HEADERS=1` set in  docker-compose.yml and docker-compose.gpu.yml. I also have `ENABLE_HTTPS=1` in docker-compose.https.yml and set `CERTBOT_DOMAIN=https://spleeter.domain.cc`. I have also removed "https://" and the result is still the same. 

There are no errors in the logs.

**Comment by JeffreyCA** [comment]
What browser are you using?

If you open the dev tools and go to networking, are the `Cross-Origin-Embedder-Policy` and `Cross-Origin-Opener-Policy` response headers being set?
<img width="646" alt="Screenshot 2024-12-01 at 4 18 30 PM" src="https://github.com/user-attachments/assets/ffc715e4-413e-4dbf-967a-3024235ef91c">

**Comment by JeffreyCA** [comment]
Also did you also set the `CERTBOT_EMAIL` variable?

> To enable HTTPS, set **both** `CERTBOT_DOMAIN` and `CERTBOT_EMAIL` to your domain name and `CERTBOT_EMAIL` to your email in `.env` and include `-f docker-compose.https.yml` in your `docker-compose up` command.

**Comment by F1zzyD** [comment]
Never mind, I just restarted my server and now the export button is there.... weird....
