### ISSUE TITLE
Can't load save_path when it is None.

### ISSUE THREAD

**Issue by DMB-codegang** [JeffreyCA/spleeter-web#135]
Both dynamic and static will be reported“Can't load save_path when it is None.“

**Comment by JeffreyCA** [comment]
Is this when using Spleeter?
Can you login to the celery-slow container and delete the `/webapp/pretrained_models/4stems` folder?

**Comment by DMB-codegang** [comment]
https://mc.codegang.top/file/pic.png

**Comment by DMB-codegang** [comment]
I can't find this folder

**Comment by JeffreyCA** [comment]
Can you share logs from the Celery process?

If you're using Docker, what does this return?

```
docker exec -it spleeter-web-celery-slow-1 ls -la /webapp/pretrained_models
```

**Comment by DMB-codegang** [comment]
I've just tried. This error occurs only in the spleeter model

**Comment by JeffreyCA** [comment]
I think this is similar: https://github.com/deezer/spleeter/issues/306

You may need to download and extract https://github.com/deezer/spleeter/releases/download/v1.4.0/4stems.tar.gz yourself and copy it to `/webapp/pretrained_models`, not sure why it's not downloading the model automatically.

**Comment by JeffreyCA** [comment]
Hi, sorry for the late reply. Could you clarify the issue, and provide logs if possible?
