### ISSUE TITLE
NPM Dependency Vulnerabilities | Reduce Network Attack Surface

### ISSUE THREAD

**Issue by Ma5onic** [JeffreyCA/spleeter-web#143]
## Dependency Vulnerabilities

During the installation, I noticed a couple of misconfigurations that introduce vulnerabilities & increase the attack surface of the application.

As you can see, there are vulnerable npm packages that were found (16 vulnerabilities (11 high, 5 critical)):
```
docker-compose -f docker-compose.gpu.yml -f docker-compose.build.gpu.yml -f docker-compose.prod.yml -f docker-compose.prod.selfhost.yml up --build
Building frontend
Sending build context to Docker daemon  1.348MB
Step 1/11 : FROM node:14-buster
14-buster: Pulling from library/node
85bed84afb9a: Pull complete 
5fdd409f4b2b: Pull complete 
fa3069e6cecf: Pull complete 
4ee16f45eff9: Pull complete 
2cee68386155: Pull complete 
0aa7befa4a1b: Pull complete 
7e71d635856c: Pull complete 
2a91b09397b6: Pull complete 
5121b8ade687: Pull complete 
Digest: sha256:aff5b535a1b25258a5ab14afda661ac781a63f3d29d3b062972c59dd1734dd6c
Status: Downloaded newer image for node:14-buster
 ---> 579449502e7e
Step 2/11 : RUN mkdir -p /webapp/frontend/assets
 ---> Running in 44035ff96a34
Removing intermediate container 44035ff96a34
 ---> 384c27d81999
Step 3/11 : WORKDIR /webapp/frontend
 ---> Running in b7e96499d92f
Removing intermediate container b7e96499d92f
 ---> 07bff07eba16
Step 4/11 : COPY package.json /webapp/frontend/
 ---> e94309d1ad61
Step 5/11 : COPY package-lock.json /webapp/frontend/
 ---> 33173906b95b
Step 6/11 : RUN npm install
 ---> Running in a60b7b288edf
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!

> node-sass@7.0.1 install /webapp/frontend/node_modules/node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v7.0.1/linux-x64-83_binding.node
Download complete
Binary saved to /webapp/frontend/node_modules/node-sass/vendor/linux-x64-83/binding.node
Caching binary to /root/.npm/node-sass/7.0.1/linux-x64-83_binding.node

> core-js@2.6.12 postinstall /webapp/frontend/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
> https://opencollective.com/core-js 
> https://www.patreon.com/zloirock 

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)


> node-sass@7.0.1 postinstall /webapp/frontend/node_modules/node-sass
> node scripts/build.js

Binary found at /webapp/frontend/node_modules/node-sass/vendor/linux-x64-83/binding.node
Testing binary
Binary is fine
npm WARN spleeter-web-frontend@1.0.0 No description
npm WARN spleeter-web-frontend@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/watchpack-chokidar2/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

added 1157 packages from 642 contributors and audited 1162 packages in 12.888s

98 packages are looking for funding
  run `npm fund` for details

found 16 vulnerabilities (11 high, 5 critical)
  run `npm audit fix` to fix them, or `npm audit` for details
Removing intermediate container a60b7b288edf
 ---> 03500ace3c99
Step 7/11 : COPY . .
 ---> 99a4ee596f90
Step 8/11 : COPY frontend-entrypoint.sh /usr/local/bin/
 ---> e1f7f9f25e97
Step 9/11 : RUN chmod +x /usr/local/bin/frontend-entrypoint.sh
 ---> Running in 5f5065c0a18e
Removing intermediate container 5f5065c0a18e
 ---> c913af04a5fc
Step 10/11 : RUN ln -s /usr/local/bin/frontend-entrypoint.sh /
 ---> Running in b76756223521
Removing intermediate container b76756223521
 ---> 250e05d9e2f0
Step 11/11 : ENTRYPOINT ["frontend-entrypoint.sh"]
 ---> Running in 1b4ecf179fe5
Removing intermediate container 1b4ecf179fe5
 ---> 268cdd2f8fa9
Successfully built 268cdd2f8fa9
Successfully tagged jeffreyca/spleeter-web-frontend:latest
```
## Network Vulnerabilities

I also noticed that you have been using 0.0.0.0 but I think you've been meaning to use localhost instead (127.0.0.1). When docker maps ports on 0.0.0.0 it tends to punch holes in firewalls and bypasses UFW rules, thus exposing the service on ANY (0.0.0.0) IP address. 
Ideally the service would only be accessible to the device that it's running on, and then tunnelled to a service like cloudflare, a reverse proxy, load balancer, etc. That way if the IP of the VPS is scanned with a tool like nmap, all ports will be closed on the public IP address & the service will only be accessible via it's (sub)domain:
https://blog.cloudflare.com/tunnel-for-everyone/

**Docker Punching Holes Through Your VPS Firewall? This Is How I Solved It**
https://youtu.be/Kr-3WKA1_fI

**Cloudflare Tunnel Setup Guide - Self-Hosting for EVERYONE**
https://youtu.be/hrwoKO7LMzk

**Comment by peterpt** [comment]
Not only npm packages are outdated and vulnerable , also python dependencies installed with pip are all outdated , this project should be updated to new versions of dependencies .

**Comment by JeffreyCA** [comment]
Unfortunately due to the number of Python dependencies on different separation models, it creates a situation where certain subdependencies have to be on the lowest common version because of dependency conflicts. This results in certain dependencies being "stuck" on old versions until the project maintainers of these models update *their* dependencies. The biggest source of vulnerabilities is probably Tensorflow (latest version is v2.9.1), but the official Spleeter package is still pinned to v2.5.0 so not much I can do there. Forking it could be another option but I would like to avoid that.

I tried my best to update all the dependencies without breaking anything and have setup Dependabot to auto-create PRs to update certain packages.

Thanks for pointing out the `0.0.0.0` issue, I've updated the binding address in the latest update.

**Comment by JeffreyCA** [comment]
Update: [A recent Spleeter update](https://github.com/deezer/spleeter/blob/master/CHANGELOG.md#232) relaxed several dependency requirements like Tensorflow so now Spleeter Web uses Tensorflow 2.7, which eliminates a large number of critical and high severity vulnerabilities on the Python side.

**Comment by Ma5onic** [comment]
@JeffreyCA  Awesome! Thanks for all your hard work, it's appreciated 😄
