### ISSUE TITLE
Option to save dynamic mix result as mixed file

### ISSUE THREAD

**Issue by lacouture** [JeffreyCA/spleeter-web#148]
From the Dynamic Mix page, propose a button to render the mix with the current volume settings, and download it into a single audio file, or save it as a static mix.

(BTW, thanks for this great web app!)

**Comment by JeffreyCA** [comment]
Thanks for the suggestion! I've added the ability to export Dynamic Mixes in-browser in the [latest update](https://github.com/JeffreyCA/spleeter-web/releases/tag/v3.13.0)
