### ISSUE TITLE
Deploying error

### ISSUE THREAD

**Issue by dlon450** [JeffreyCA/spleeter-web#18]
Hi,

Just wondering why the following errors pop up when I run _spleeter-web$ sudo docker-compose -f docker-compose.yml -f docker-compose.build.yml -f docker-compose.prod.yml up --build -d_ from step 4:
![image](https://user-images.githubusercontent.com/59182667/95278548-edaf0700-08ac-11eb-97f4-20b3d115b42a.png)

I am using Azure as my storage provider and have created the .env file as specified in step 3.

Thanks,
Derek

**Comment by JeffreyCA** [comment]
@dlon45 are you on Windows? The issue might be that Docker isn't running on your machine, [see this](https://stackoverflow.com/questions/42052270/docker-compose-up-gives-the-system-cannot-find-the-file-specified-error). Does that help?

**Comment by dlon450** [comment]
@JeffreyCA I think it's resolved now. I'll let you know if any other issues pop up. Thanks :)

**Comment by JeffreyCA** [comment]
Good to hear, I'll close this issue then.
