### ISSUE TITLE
I try the project many times but could not running 

### ISSUE THREAD

**Issue by Sanararax** [JeffreyCA/spleeter-web#22]
In the ubuntu19/20, centos 7, Mac os 10.14/10.15 I found a problem form the pip 
like this:
  Running command git clone -q https://github.com/JeffreyCA/youtube-dl.git /webapp/src/youtube-dl
  Running command git checkout -q 3afecd1a8c3c4371369984137389d580210c3d15
  fatal: reference is not a tree: 3afecd1a8c3c4371369984137389d580210c3d15
ERROR: Command errored out with exit status 128: git checkout -q 3afecd1a8c3c4371369984137389d580210c3d15 Check the logs for full command output.
WARNING: You are using pip version 20.1.1; however, version 20.3.1 is available.
You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
ERROR: Service 'huey' failed to build : The command '/bin/sh -c pip install --upgrade pip -r requirements.txt' returned a non-zero code: 1

The tips told the error is the pip3/pip vision was out of style, But I checked my machine and my pip is 20.3.1.
So what's the root about the pip? I'm tired, and thanks for you project.

**Comment by JeffreyCA** [comment]
Thanks for the report. I pushed an update that should fix this (https://github.com/JeffreyCA/spleeter-web/commit/4461d4715c5e800a9e7e52567f7e4ddd97c021ee). Can you do a `git pull` and try again?

**Comment by Sanararax** [comment]
Thx!I will test at now!

**Comment by Sanararax** [comment]
It's working right. THX a lot

**Comment by JeffreyCA** [comment]
Glad to hear!
