### ISSUE TITLE
Changing ports

### ISSUE THREAD

**Issue by hackerESQ** [JeffreyCA/spleeter-web#285]
I see there's a new environment variable for `NGINX_PORT`, but that only changes the default port 80.  Is there a way to update port 443 for SSL, and port 8000 for the API?

I run several other containers that conflict (an NGINX proxy on ports 80 and 443) and Portainer which uses port 8000. 

I tried manually updating the mappings in the yaml files, but ended up with Bad Request 400, just like OP in #137. Is there any way to get this working with different ports?

**Comment by hackerESQ** [comment]
Oh, and did try the `APP_HOST` solution in the `settings_docker.py` file. Tried with just ['*'] and with my host's IP address. Neither worked.

**Comment by JeffreyCA** [comment]
Port 8000 isn't exposed to the host machine (prod config) so there shouldn't be any conflicts with other containers. What issues are you facing there?

As for remapping port 443, thanks for catching that! I forgot to create an environment variable for it. I just pushed a change (https://github.com/JeffreyCA/spleeter-web/commit/97bef09f2f6ed624703482244e51911b0f9019d8) that adds a new variable `NGINX_PORT_SSL` to configure that.

Some additional changes:

- `APP_HOST` now accepts multiple comma-separated values
- `ALLOW_ALL_HOSTS` is a new variable that allows all hosts if set to `1`.

If you're still facing issues, can you try appending `192.168.0.111` to `APP_HOST`?

**Comment by hackerESQ** [comment]
Neat! Thanks for that quick update. Have to admit it was having difficultly with just setting `ALLOW_ALL_HOST`, `NGINX_PORT`, and `NGINX_SSL_PORT`. Was still running into the same 400 error.

But for some reason setting `APP_HOST` this time finally worked.  Here's my final .env file for anyone else having trouble:

```
ALLOW_ALL_HOSTS=1
NGINX_PORT=9081
NGINX_PORT_SSL=9043
APP_HOST=192.168.0.111
```

**Comment by JeffreyCA** [comment]
Oops my bad, I didn't define `ALLOW_ALL_HOSTS` in the Docker Compose files, it should work now with the latest changes 😅 (official Django docs mention [some potential security implications](https://docs.djangoproject.com/en/4.1/ref/settings/#allowed-hosts) of doing so).

Good to hear that worked!
