### ISSUE TITLE
Bad Request (400)

### ISSUE THREAD

**Issue by 603000** [JeffreyCA/spleeter-web#318]
Hi,
I tried multiple times installing your tool on VPS and everytime I get "Bad Request (400)".
What can cause this problem?

**Comment by JeffreyCA** [comment]
Do you see any errors in the Docker logs?

**Comment by 603000** [comment]
Thank you,
checked the logs and it looks like the problem is in this:

Invalid HTTP_HOST header: 'my ip address'. 
You may need to add 'my ip address' to ALLOWED_HOSTS.

But added my server ip address in .env as a APP_HOST=...

Could you please help where should I look to fix this problem?

**Comment by JeffreyCA** [comment]
Are you using Docker? If so what's the command you're running?

Just for testing purposes, does it work if you set `ALLOW_ALL_HOSTS=1` in `.env`?

**Comment by 603000** [comment]
Thank you, fixed!
