### ISSUE TITLE
Infinite processing time

### ISSUE THREAD

**Issue by 603000** [JeffreyCA/spleeter-web#323]
I'm trying to run the app on the VPS with 4 vCPU Cores and 8 GB RAM.
Either static mix or dymanic mix with any model is processed indefinitely. No errors (except for Splitter model - screenshot attached) just infinite processing time - you can wait hours with no result.

What can cause these problems - processing time and errors with Splitter model?

<img width="868" alt="Screenshot_4" src="https://user-images.githubusercontent.com/73283886/195344842-c5d25b53-48c5-43d8-b554-654749f4cbb4.png">

**Comment by JeffreyCA** [comment]
What command are you running?

**Comment by JeffreyCA** [comment]
I meant the command to start the application (e.g. `docker-compose` command)

**Comment by 603000** [comment]
I made everything according to instruction in the "deployment" section - If you are self-hosting media files:

# Use prebuilt images
spleeter-web$ sudo docker-compose -f docker-compose.yml -f docker-compose.prod.yml -f docker-compose.prod.selfhost.yml up -d

**Comment by JeffreyCA** [comment]
Are you able to play the uploaded songs?

Can you share the logs from the Docker command? Espcially logs from `spleeter-web-celery-slow-1`

**Comment by 603000** [comment]
No, uploaded songs don't play.
Here is the log.
[log.txt](https://github.com/JeffreyCA/spleeter-web/files/9776005/log.txt)

**Comment by 603000** [comment]
media/uploads/ is empty
Uploaded new file, here are the logs
[log1.txt](https://github.com/JeffreyCA/spleeter-web/files/9779776/log1.txt)

**Comment by JeffreyCA** [comment]
It looks like an issue with the Docker bind mount not working.

Are you running the docker-compose command as root? If not maybe check that the user has permission to write to the media folder on your host machine.

One other thing you can try is to run Spleeter Web without the selfhost.yml and upload a song, does that work?

**Comment by 603000** [comment]
It's definitely as root (it was clean vps and no other users were created).
Sadly but I tried renaming docker-compose.prod.selfhost.yml and restarted all containers but result is the same.

**Comment by JeffreyCA** [comment]
I'm unfortunately not able to repro the issue. What's your host OS? 

Can you try deleting everything and restart again:

1. `sudo docker compose down <.yml files>`
2. `sudo docker system prune --all`
3. `sudo docker volume prune`
4. `sudo docker compose up <.yml files>`?

**Comment by 603000** [comment]
My OS is Ubuntu 20.04 (64 Bit).
Sadly, nothning helps. I tried full reinstall and got same result. Looks like I do something wrong.
Can I ask you for paid help installing your app on my server?  We can discuss it via email - ads_corp@yahoo.com or you can leave your contacts and I'll reach for you. Thank you!

**Comment by JeffreyCA** [comment]
Sure feel free to drop a mail [here](mailto:jeffreyca16@gmail.com)

**Comment by JeffreyCA** [comment]
Resolved offline - spleeter separation task terminated early likely due to insufficient memory
