### ISSUE TITLE
Support demucs v4

### ISSUE THREAD

**Issue by lekoOwO** [JeffreyCA/spleeter-web#393]
demucs v4 has released.

Is there any plans of supporting it?
Thanks!

**Comment by JeffreyCA** [comment]
Hi, thanks I'll probably look into it - it's still bleeding edge/hasn't been published on [PyPI](https://pypi.org/project/demucs/#history) so it might not be 100% stable

**Comment by JeffreyCA** [comment]
Just added support for v4 in the latest update 🙂
