### ISSUE TITLE
In file './docker-compose.yml', service 'x-celery-env' must be a mapping not an array.

### ISSUE THREAD

**Issue by m2dsa** [JeffreyCA/spleeter-web#400]
Hi,
I tried to install your app according to instructions but when I try to put 
spleeter-web$ sudo docker-compose -f docker-compose.yml -f docker-compose.prod.yml -f docker-compose.prod.selfhost.yml up -d

I receive the following error - In file './docker-compose.yml', service 'x-celery-env' must be a mapping not an array.

Could you help with this?

**Comment by JeffreyCA** [comment]
Hi, can you make sure you have the [latest version](https://docs.docker.com/compose/release-notes/) of Docker Compose installed?

**Comment by m2dsa** [comment]
Sorry, you said about Docker Compose, my version is docker-compose version 1.25.0

**Comment by JeffreyCA** [comment]
Can you try installing a newer version? It might not be compatible with the syntax

**Comment by m2dsa** [comment]
Yes, it helped. Thank you!
