### ISSUE TITLE
Max File size too small

### ISSUE THREAD

**Issue by dts350z** [JeffreyCA/spleeter-web#423]
Need an environment variable to set max file size.

What is the current limit?

It's currently too small to support 24 minutes of audio, even with flac level 8 compression.

**Comment by JeffreyCA** [comment]
I've added two variables `UPLOAD_FILE_SIZE_LIMIT` (size in MB) and YOUTUBE_LENGTH_LIMIT (length in minutes) to be able to configure upload limits in https://github.com/JeffreyCA/spleeter-web/commit/00993e9556dac8b2198a40d7d0812b75d71a8bcf.
