### ISSUE TITLE
Additional pages

### ISSUE THREAD

**Issue by m2dsa** [JeffreyCA/spleeter-web#452]
Hi,
as I understand this is React App with a single page (great app, by the way). 
Is there a really simple way to add additional pages and make them accesible from the front page?

**Comment by JeffreyCA** [comment]
Hi, you can create a React component for your page (they're kept in [`frontend/src/components`](https://github.com/JeffreyCA/spleeter-web/tree/master/frontend/src/components)) and configure the routing (ReactRouter) in [`frontend/src/index.ts`](https://github.com/JeffreyCA/spleeter-web/blob/master/frontend/src/index.tsx).
