### ISSUE TITLE
Invalid Youtube Link / MIME type not allowed

### ISSUE THREAD

**Issue by JustDalek** [JeffreyCA/spleeter-web#519]
Hello!

I have spleeter web deployed with the GPU script. It had worked for some time but yesterday I attempted to use a youtube url and it failed to work. I then downloaded the video as an mp3 and tried to upload that, also fails

I deleted the container, all images, and drive data in my docker
I also deleted the prior git cloned dir, and ran a fresh clone, fresh install

This is my YT URL: https://www.youtube.com/watch?v=ugoobA-TbRA

Here are my errors:
<img width="278" alt="image" src="https://user-images.githubusercontent.com/78516780/221585234-2025b270-9cbd-4ec7-9858-1f89f3464717.png">
<img width="297" alt="image" src="https://user-images.githubusercontent.com/78516780/221585292-b0c543cf-eb32-4d8a-9a33-afc5e6ca8bb6.png">

**Comment by JustDalek** [comment]
Also happens with this URL
https://www.youtube.com/watch?v=eJlN9jdQFSc

And M4a files

**Comment by JeffreyCA** [comment]
Thanks for the report, I've updated the yt-dlp dependency and should work now.

**Comment by JustDalek** [comment]
Confirmed I can upload items now thank you!
