### ISSUE TITLE
Help with spleeter training

### ISSUE THREAD

**Issue by rikishi0071** [JeffreyCA/spleeter-web#53]
Hi! I'm inspired by your project but I cannot find any information (step by step algorythm) how to train my own model by .wav tracks collection with spleeter. I know something like .csv and .json files are needed. Can you help me please? I ll collect .wav tracks and you will train model in spleeter. 4stems model is good but doesn't work well

**Comment by JeffreyCA** [comment]
Hi, I think your question is more appropriate for the original spleeter project: https://github.com/deezer/spleeter/issues
This project does not concern training models with Spleeter.
