### ISSUE TITLE
SSL CERTBOT www. issue

### ISSUE THREAD

**Issue by vah7id** [JeffreyCA/spleeter-web#532]
server {
    listen 443 ssl http2;
    client_max_body_size ${UPLOAD_FILE_SIZE_LIMIT}M;

    ssl_certificate         /etc/letsencrypt/live/${CERTBOT_DOMAIN}/fullchain.pem;
    ssl_certificate_key     /etc/letsencrypt/live/${CERTBOT_DOMAIN}/privkey.pem;
    ssl_trusted_certificate /etc/letsencrypt/live/${CERTBOT_DOMAIN}/chain.pem;

    server_name ${CERTBOT_DOMAIN};

    location / {
        proxy_pass http://django_react;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Host $host;
        proxy_set_header Authorization "";
        proxy_redirect off;

        # allow <ip>;
        # deny all;
    }
}

I was wondering If we need to add www. manually in the ssl config file nexto CERTBOT_DOMAIN to be able to turn the ssl on?
Rightnow my site works perfectly https://domain.com but when I try to go with www.domain.com I get the SSL private error!

Do we need to change the CERTBOT_DOMAIN name to CERTBOT_DOMAINS and cover list of domain instead?

**Comment by JeffreyCA** [comment]
Thanks for reporting, I made a small fix in !533 - can you try setting `CERTBOT_DOMAIN` to a list of domains surrounded by quotes like so:

```
CERTBOT_DOMAIN="mydomain.com www.mydomain.com"
```

**Comment by vah7id** [comment]
@JeffreyCA Thanks a lot just checked out the MR and that worked out for me and also fixed the ssl CERBOT issue with www. CNAME!

**Comment by JeffreyCA** [comment]
Great, thanks for confirming! Closing as resolved.
