### ISSUE TITLE
join() argument must be str, bytes, or os.PathLike object, not 'UUID'

### ISSUE THREAD

**Issue by atlury** [JeffreyCA/spleeter-web#672]
I get the following issue while using the last cpu version (prebuilt version). Has latest docker and docker compose and ubuntu 20.04. Built from source, changed OS versions, changed various docker versions and still the same

**Comment by atlury** [comment]
> spleeter-web-celery-fast-1  | [2023-06-28 06:24:34,284: WARNING/ForkPoolWorker-1] [download] Destination: media/uploads/ac29da48-305e-4901-aac3-5461c740a1f3/DiscoDancer - disco-dancer.webm
> spleeter-web-celery-fast-1  |
> [download]   0.0% of ~   5.46MiB at    8.14KiB/s ETA 11:27 (frag 0/1)oolWorker-1]
> [download]   0.1% of ~   5.46MiB at   24.16KiB/s ETA 03:51 (frag 0/1)oolWorker-1]
> [download]   0.1% of ~   5.46MiB at   55.91KiB/s ETA 01:39 (frag 0/1)oolWorker-1]
> [download]   0.3% of ~   5.46MiB at  118.80KiB/s ETA 00:46 (frag 0/1)oolWorker-1]
> [download]   0.6% of ~   5.46MiB at  232.84KiB/s ETA 00:23 (frag 0/1)oolWorker-1]
> [download]   1.1% of ~   5.46MiB at  439.71KiB/s ETA 00:12 (frag 0/1)oolWorker-1]
> [download]   2.3% of ~   5.46MiB at  814.31KiB/s ETA 00:06 (frag 0/1)oolWorker-1]
> [download]   4.6% of ~   5.46MiB at    1.49MiB/s ETA 00:03 (frag 0/1)oolWorker-1]
> [download]   9.1% of ~   5.46MiB at    2.76MiB/s ETA 00:01 (frag 0/1)oolWorker-1]
> [download]  18.3% of ~   5.46MiB at    5.14MiB/s ETA 00:00 (frag 0/1)oolWorker-1]
> [download]  36.6% of ~   5.46MiB at    9.04MiB/s ETA 00:00 (frag 0/1)oolWorker-1]
> [download]  73.2% of ~   5.46MiB at   15.77MiB/s ETA 00:00 (frag 0/1)oolWorker-1]
> [download] 100.0% of ~   5.46MiB at   20.31MiB/s ETA 00:00 (frag 0/1)oolWorker-1]
> [download] 100.0% of ~   5.46MiB at   20.15MiB/s ETA 00:00 (frag 1/1)oolWorker-1]
> [download] 100% of    5.46MiB in 00:00:00 at 19.44MiB/s              oolWorker-1]
> spleeter-web-celery-fast-1  | [2023-06-28 06:24:34,567: WARNING/ForkPoolWorker-1]
> spleeter-web-celery-fast-1  |
> spleeter-web-celery-fast-1  | [2023-06-28 06:24:34,646: INFO/ForkPoolWorker-1] Task api.tasks.fetch_youtube_audio[e73b4b8f-e95f-4b26-b743-789690618342] succeeded in 4.707064683999988s: None
> spleeter-web-nginx-1        | 49.205.249.167 - - [28/Jun/2023:06:24:39 +0000] "GET /api/source-track/ HTTP/1.1" 200 365 "http://115.248.56.2:9090/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 Edg/114.0.1823.58" "-"
> spleeter-web-celery-slow-1  | [2023-06-28 06:24:49,512: INFO/MainProcess] Task api.tasks.create_dynamic_mix[c43749bd-d908-4a69-be3e-662619b4d515] received
> spleeter-web-nginx-1        | 49.205.249.167 - - [28/Jun/2023:06:24:49 +0000] "POST /api/mix/dynamic/ HTTP/1.1" 201 455 "http://115.248.56.2:9090/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 Edg/114.0.1823.58" "-"
> spleeter-web-celery-slow-1  | [2023-06-28 06:24:49,528: WARNING/ForkPoolWorker-1] join() argument must be str, bytes, or os.PathLike object, not 'UUID'
> spleeter-web-celery-slow-1  | [2023-06-28 06:24:49,528: WARNING/ForkPoolWorker-1]
> spleeter-web-celery-slow-1  |
> spleeter-web-celery-slow-1  | [2023-06-28 06:24:49,536: INFO/ForkPoolWorker-1] Task api.tasks.create_dynamic_mix[c43749bd-d908-4a69-be3e-662619b4d515] succeeded in 0.022442483000077118s: None
>

**Comment by atlury** [comment]
btw the system is 16-core, 32gb ram with 1tb ssd.

**Comment by triscuitcircuit** [comment]
Same issue here on Windows 11 using Docker

**Comment by JeffreyCA** [comment]
Thanks all for the report, just fixed this in 02f990cec2f77770ec8b82b7dde89099384741c9. There was [a breaking change in `kombu`](https://github.com/celery/kombu/issues/1749), a transitive dependency of Celery. Can you pull the latest and check that it works now?

**Comment by atlury** [comment]
yes right away....

**Comment by atlury** [comment]
it works now, thanks a bunch!

**Comment by JeffreyCA** [comment]
Thanks for confirming! Closing as resolved
