### ISSUE TITLE
Security issue with ALLOW_ALL_HOST

### ISSUE THREAD

**Issue by vah7id** [JeffreyCA/spleeter-web#873]
@JeffreyCA 
I'm facing an issue from my cloud provider that says your app committing denial of service (DoS) attacks and I was wondering if ALLOW_ALL_HOST=1 in my configuration could possibly cause that issue?
Or not what else could it be the solution to prevent that issue? Maybe putting all the files on cloud DNS would be the fix?

**Comment by JeffreyCA** [comment]
Do you have more details on what what resources are getting hit with DoS? Are you selfhosting the files or using cloud storage?

Setting ALLOW_ALL_HOSTS does come with security risks, as outliend in the README. Can you use `ALLOWED_HOSTS` setting instead and set all the required hostnames individually?

**Comment by vah7id** [comment]
That worked out by setting ALLOWED_HOSTS.

**Comment by JeffreyCA** [comment]
Thanks for confirming
