### ISSUE TITLE
Anaconda Navigator Start-Up

### ISSUE THREAD

**Issue by amarsinghbist** [JeffreyCA/spleeter-web#93]
Hello All,

I installed Anaconda 3.8. I can open the Anaconda Prompt and import files etc.. But I can't open Anaconda navigator.
I am facingproble as below.

Main Error
check_hostname requires server_hostname

Please suggest a solution.

**Comment by JeffreyCA** [comment]
Hi, I cannot guarantee Spleeter Web works with Anaconda. Please use one of the two supported approaches to run Spleeter Web: [Docker](https://github.com/JeffreyCA/spleeter-web#getting-started-with-docker) and [non-Docker](https://github.com/JeffreyCA/spleeter-web#getting-started-without-docker)

**Comment by amarsinghbist** [comment]
> Hi, I cannot guarantee Spleeter Web works with Anaconda. Please use one of the two supported approaches to run Spleeter Web: [Docker](https://github.com/JeffreyCA/spleeter-web#getting-started-with-docker) and [non-Docker](https://github.com/JeffreyCA/spleeter-web#getting-started-without-docker)

Hi.
Sorry, I didn't get your reply. My query was that, I am not able to open Anaconda navigator in my PC but your replied about spleeter web?

**Comment by JeffreyCA** [comment]
> > Hi, I cannot guarantee Spleeter Web works with Anaconda. Please use one of the two supported approaches to run Spleeter Web: [Docker](https://github.com/JeffreyCA/spleeter-web#getting-started-with-docker) and [non-Docker](https://github.com/JeffreyCA/spleeter-web#getting-started-without-docker)
> 
> Hi.
> Sorry, I didn't get your reply. My query was that, I am not able to open Anaconda navigator in my PC but your replied about spleeter web?

Then this is the wrong place to report this. You can check this out: https://docs.anaconda.com/anaconda/navigator/help-support/
