### ISSUE TITLE
Export of mixes does not work on iOS

### ISSUE THREAD

**Issue by microtherion** [JeffreyCA/spleeter-web#996]
The export button in the mixer is always disabled on iOS. It appears that the memory allocation `new WebAssembly.Memory` in `createFFmpegCore` fails. I was unable to track this any further, due to my unfamiliarity with the code.

**Comment by microtherion** [comment]
I think I found the likely cause: Your fork of `ffmpeg.wasm` does not include https://github.com/ffmpegwasm/ffmpeg.wasm-core/pull/15 which was the upstream fix for this issue.

**Comment by JeffreyCA** [comment]
> I think I found the likely cause: Your fork of `ffmpeg.wasm` does not include [ffmpegwasm/ffmpeg.wasm-core#15](https://github.com/ffmpegwasm/ffmpeg.wasm-core/pull/15) which was the upstream fix for this issue.

Thanks for figuring it out! I updated the fork with those changes [here](https://github.com/JeffreyCA/ffmpeg.wasm-core/releases/tag/v0.11.0-jeffreyca) and bumped the package version to consume it
